import type { VisualNovel } from "@gal-yiba/shared";

/**
 * 开发/演示用题库：仅在未配置 DATABASE_URL 的内存模式下返回，
 * 让本地可以直接开局测试单人/每日/房间玩法。
 */
const demoCatalogEntries: Array<Omit<VisualNovel, "isOtome">> = [
  {
    id: "10000000-0000-4000-8000-000000000001",
    title: "CLANNAD",
    aliases: ["家族"],
    developer: ["Key"],
    publisher: ["Visual Arts"],
    scenarioWriter: ["麻枝准"],
    heroineHairColor: ["multicolored"],
    releaseYear: 2004,
    playtime: "long",
    vndbRating: 8.5,
    bangumiRating: 8.6,
    vndbVoteCount: 850,
    bangumiVoteCount: 900,
    animeAdaptation: "has_adaptation",
    ageRating: "all_ages",
    platforms: ["windows", "ps2"],
    languages: ["ja", "zh-Hans"],
    tags: ["校园", "亲情", "奇幻"],
    provenance: {},
  },
  {
    id: "10000000-0000-4000-8000-000000000002",
    title: "Katawa Shoujo",
    aliases: ["片轮少女"],
    developer: ["Four Leaf Studios"],
    publisher: null,
    scenarioWriter: null,
    heroineHairColor: ["multicolored"],
    releaseYear: 2012,
    playtime: "medium",
    vndbRating: 7.8,
    bangumiRating: 7.5,
    vndbVoteCount: 700,
    bangumiVoteCount: 600,
    animeAdaptation: null,
    ageRating: "all_ages",
    platforms: ["windows"],
    languages: ["en", "zh-Hans"],
    tags: ["校园", "恋爱", "治愈"],
    provenance: {},
  },
  {
    id: "10000000-0000-4000-8000-000000000003",
    title: "Fate/stay night",
    aliases: ["命运长夜", "フェイト"],
    developer: ["TYPE-MOON"],
    publisher: null,
    scenarioWriter: ["奈須きのこ"],
    heroineHairColor: ["multicolored"],
    releaseYear: 2004,
    playtime: "long",
    vndbRating: 7.9,
    bangumiRating: 8.0,
    vndbVoteCount: 800,
    bangumiVoteCount: 750,
    animeAdaptation: "has_adaptation",
    ageRating: "restricted",
    platforms: ["windows", "ps2"],
    languages: ["ja"],
    tags: ["奇幻", "战斗", "月姬"],
    provenance: {},
  },
  {
    id: "10000000-0000-4000-8000-000000000004",
    title: "千恋＊万花",
    aliases: ["Senren Banka", "千恋万花"],
    developer: ["Yuzusoft"],
    publisher: null,
    scenarioWriter: null,
    heroineHairColor: ["multicolored"],
    releaseYear: 2016,
    playtime: "long",
    vndbRating: 8.1,
    bangumiRating: 7.8,
    vndbVoteCount: 600,
    bangumiVoteCount: 850,
    animeAdaptation: null,
    ageRating: "restricted",
    platforms: ["windows"],
    languages: ["ja", "zh-Hans"],
    tags: ["和风", "恋爱", "刀剑"],
    provenance: {},
  },
  {
    id: "10000000-0000-4000-8000-000000000005",
    title: "Summer Pockets REFLECTION BLUE",
    aliases: ["夏日口袋", "夏日重现"],
    developer: ["Key"],
    publisher: ["Visual Arts"],
    scenarioWriter: ["麻枝准"],
    heroineHairColor: ["multicolored"],
    releaseYear: 2021,
    playtime: "long",
    vndbRating: 8.3,
    bangumiRating: 8.2,
    vndbVoteCount: 650,
    bangumiVoteCount: 700,
    animeAdaptation: "has_adaptation",
    ageRating: "all_ages",
    platforms: ["windows", "switch"],
    languages: ["ja", "zh-Hans"],
    tags: ["夏日", "亲情", "奇幻"],
    provenance: {},
  },
  {
    id: "10000000-0000-4000-8000-000000000006",
    title: "STEINS;GATE",
    aliases: ["命运石之门", "シュタインズ・ゲート"],
    developer: ["5pb."],
    publisher: null,
    scenarioWriter: null,
    heroineHairColor: ["multicolored"],
    releaseYear: 2011,
    playtime: "long",
    vndbRating: 8.9,
    bangumiRating: 8.9,
    vndbVoteCount: 900,
    bangumiVoteCount: 900,
    animeAdaptation: "has_adaptation",
    ageRating: "all_ages",
    platforms: ["windows", "ps3"],
    languages: ["ja", "zh-Hans"],
    tags: ["科幻", "时间旅行", "悬疑"],
    provenance: {},
  },
  {
    id: "10000000-0000-4000-8000-000000000007",
    title: "AIR",
    aliases: ["青空", "エアー"],
    developer: ["Key"],
    publisher: ["Visual Arts"],
    scenarioWriter: null,
    heroineHairColor: ["multicolored"],
    releaseYear: 2000,
    playtime: "medium",
    vndbRating: 8.2,
    bangumiRating: 8.0,
    vndbVoteCount: 550,
    bangumiVoteCount: 500,
    animeAdaptation: "has_adaptation",
    ageRating: "all_ages",
    platforms: ["windows"],
    languages: ["ja"],
    tags: ["夏天", "亲情", "奇幻"],
    provenance: {},
  },
  {
    id: "10000000-0000-4000-8000-000000000008",
    title: "Ever17 -the out of infinity-",
    aliases: ["时空轮回", "エバー17"],
    developer: ["KID"],
    publisher: null,
    scenarioWriter: null,
    heroineHairColor: ["multicolored"],
    releaseYear: 2002,
    playtime: "medium",
    vndbRating: 8.7,
    bangumiRating: 8.3,
    vndbVoteCount: 750,
    bangumiVoteCount: 650,
    animeAdaptation: null,
    ageRating: "all_ages",
    platforms: ["windows", "ps2"],
    languages: ["ja"],
    tags: ["科幻", "密室", "悬疑"],
    provenance: {},
  },
  {
    id: "10000000-0000-4000-8000-000000000009",
    title: "WHITE ALBUM 2",
    aliases: ["白色相簿2", "ホワイトアルバム2"],
    developer: ["Leaf"],
    publisher: null,
    scenarioWriter: null,
    heroineHairColor: ["multicolored"],
    releaseYear: 2010,
    playtime: "long",
    vndbRating: 8.6,
    bangumiRating: 8.4,
    vndbVoteCount: 700,
    bangumiVoteCount: 800,
    animeAdaptation: "has_adaptation",
    ageRating: "all_ages",
    platforms: ["windows", "ps3"],
    languages: ["ja", "zh-Hans"],
    tags: ["校园", "音乐", "恋爱"],
    provenance: {},
  },
  {
    id: "10000000-0000-4000-8000-000000000010",
    title: "Yosuga no Sora",
    aliases: ["缘之空", "ヨスガノソラ"],
    developer: ["Sphere"],
    publisher: null,
    scenarioWriter: null,
    heroineHairColor: ["multicolored"],
    releaseYear: 2008,
    playtime: "medium",
    vndbRating: 6.9,
    bangumiRating: 6.8,
    vndbVoteCount: 450,
    bangumiVoteCount: 400,
    animeAdaptation: "has_adaptation",
    ageRating: "restricted",
    platforms: ["windows"],
    languages: ["ja"],
    tags: ["兄妹", "恋爱", "夏"],
    provenance: {},
  },
  {
    id: "10000000-0000-4000-8000-000000000011",
    title: "Himawari no Kanojo",
    aliases: ["向日葵的教会与长长暑假", "ひまわりの彼女"],
    developer: ["Sphere"],
    publisher: null,
    scenarioWriter: null,
    heroineHairColor: ["multicolored"],
    releaseYear: 2010,
    playtime: "medium",
    vndbRating: 7.5,
    bangumiRating: 7.3,
    vndbVoteCount: 300,
    bangumiVoteCount: 350,
    animeAdaptation: null,
    ageRating: "restricted",
    platforms: ["windows"],
    languages: ["ja"],
    tags: ["夏日", "教堂", "恋爱"],
    provenance: {},
  },
  {
    id: "10000000-0000-4000-8000-000000000012",
    title: "Rewrite",
    aliases: ["リライト"],
    developer: ["Key"],
    publisher: ["Visual Arts"],
    scenarioWriter: ["田中ロミオ"],
    heroineHairColor: ["multicolored"],
    releaseYear: 2011,
    playtime: "very_long",
    vndbRating: 8.0,
    bangumiRating: 7.9,
    vndbVoteCount: 500,
    bangumiVoteCount: 550,
    animeAdaptation: "has_adaptation",
    ageRating: "all_ages",
    platforms: ["windows"],
    languages: ["ja"],
    tags: ["校园", "奇幻", "环保"],
    provenance: {},
  },
];

export const demoCatalog: VisualNovel[] = demoCatalogEntries.map((entry) => ({
  ...entry,
  isOtome: false,
}));
